name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    services:
      # Run OpenS3 as a service container
      opens3:
        image: sourcebox/opens3:latest  # Replace with actual image when available
        ports:
          - 8001:8001
        env:
          OPENS3_ACCESS_KEY: admin
          OPENS3_SECRET_KEY: password
        options: >-
          --health-cmd "curl -f http://localhost:8001/ || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      
      - name: Set up OpenS3 integration environment
        run: |
          export S3_ENDPOINT="http://localhost:8001"
          export OPENS3_ACCESS_KEY="admin"
          export OPENS3_SECRET_KEY="password"
          
          # Create test bucket and upload test data
          python -c "
          import requests
          import json

          # Create test buckets
          headers = {'Content-Type': 'application/json'}
          
          # Create world-pop bucket
          response = requests.post(
              'http://localhost:8001/buckets',
              headers=headers,
              json={'name': 'world-pop'},
              auth=('admin', 'password')
          )
          print(f'Create world-pop bucket: {response.status_code}')
          
          # Create test-analytics bucket
          response = requests.post(
              'http://localhost:8001/buckets',
              headers=headers,
              json={'name': 'test-analytics'},
              auth=('admin', 'password')
          )
          print(f'Create test-analytics bucket: {response.status_code}')
          "
          
      - name: Run Integration Tests
        run: |
          # Set necessary environment variables
          export S3_ENDPOINT="http://localhost:8001"
          export OPENS3_ACCESS_KEY="admin"
          export OPENS3_SECRET_KEY="password"
          
          # Start OpenAthena server for testing
          python -m open_athena.main &
          sleep 5  # Give time for server to start
          
          # Run integration tests
          pytest tests/integration/
          
      - name: Collect and upload test artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-logs
          path: |
            logs/
            integration_tests_report.xml
          retention-days: 7
