name: Lint & Auto-fix

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0           # needed for push
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install linters + autofixer
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort mypy autoflake
          pip install -r requirements.txt

      - name: Auto-remove unused imports & variables
        run: |
          autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive .

      - name: Sort imports
        run: |
          isort .

      - name: Reformat with Black
        run: |
          black . --exclude="src/.*"

      - name: Type check
        run: |
          mypy --ignore-missing-imports open_athena/

      - name: Commit & push auto-fixes
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: apply auto-fix linting"
          git push
