name: Lint & Auto-fix
on:
  push:     { branches: [master] }
  pull_request: { branches: [master] }
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          submodules: recursive      # only if you kept the real submodule

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install linters + autofixer
        run: |
          python -m pip install --upgrade pip
          pip install autoflake isort black mypy
          pip install -r requirements.txt

      - name: Auto-remove unused imports & vars
        run: |
          # if you kept submodule, exclude it
          autoflake \
            --in-place \
            --remove-all-unused-imports \
            --remove-unused-variables \
            --recursive \
            ${GITHUB_WORKSPACE} \
            --exclude src/open-athena

      - name: Sort imports
        run: |
          isort . --skip src/open-athena

      - name: Reformat with Black
        run: |
          black . --exclude "src/open-athena|src/.*"

      - name: Type check
        run: |
          mypy --ignore-missing-imports open_athena/

      - name: Commit & push auto-fixes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: apply auto-fix linting"
          git push origin HEAD:master
