name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort mypy
          pip install -r requirements.txt
          
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      - name: Auto-format with black
        run: |
          black .
          
      - name: Auto-sort imports with isort
        run: |
          isort .
          
      - name: Commit formatting changes if needed
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          # Remove accidental git repository if it exists
          if [ -d "src/open-athena/.git" ]; then
            rm -rf src/open-athena/.git
          fi
          
          if [[ -n $(git status --porcelain) ]]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add .
            git commit -m "Auto-format code with Black and isort"
            # Use token for authentication
            git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git push
          fi
          
      - name: Type check with mypy
        run: |
          mypy --ignore-missing-imports open_athena/
